name: Test Node.js App
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on:  ubuntu-latest
    env:  # Define environment variables here
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "job_match_db"
      DB_PORT: "5432"
      PORT: "3000"
      JWT_SEED: "secretToken"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: List Directory Contents
        run: ls

      - name: Install dependencies
        run: npm ci

      - name: Build and Run Docker Compose
        run: |
          docker-compose up -d
        working-directory: .

      - name: Run tests
        run: npm run test
